<template>
  <div id="disclosures">
    <h1>Risk Warnings and Disclosures</h1>
    <br />
    <div class="flex-container">
      <div class="para">
        <p>CAMBRIDGE GLOBAL PAYMENTS (“CAMBRIDGE”) PROVIDES THIS DOCUMENT AS GENERAL MARKET INFORMATION SUBJECT TO: CAMBRIDGE’S COPYRIGHT, AND ALL CONTRACT TERMS IN PLACE, IF ANY, BETWEEN YOU AND THE CAMBRIDGE ENTITY YOU HAVE CONTRACTED WITH. THIS DOCUMENT IS BASED ON SOURCES CAMBRIDGE CONSIDERS RELIABLE, BUT WITHOUT INDEPENDENT VERIFICATION. CAMBRIDGE MAKES NO GUARANTEE OF ITS ACCURACY OR COMPLETENESS. CAMBRIDGE IS NOT RESPONSIBLE FOR ANY ERRORS IN OR RELATED TO THE DOCUMENT, OR FOR DAMAGES ARISING OUT OF ANY PERSON’S RELIANCE UPON THIS INFORMATION. ALL CHARTS OR GRAPHS ARE FROM PUBLICLY AVAILABLE SOURCES OR PROPRIETARY DATA. THE INFORMATION IN THIS DOCUMENT IS SUBJECT TO SUDDEN CHANGE WITHOUT NOTICE. “CAMBRIDGE GLOBAL PAYMENTS” IS A TRADE NAME, WHICH IN THIS DOCUMENT REFERS SPECIFICALLY TO ONE OR MORE OF THESE LEGAL ENTITIES: CAMBRIDGE MERCANTILE CORP., CAMBRIDGE MERCANTILE CORP. (U.S.A.), CAMBRIDGE MERCANTILE CORP. (NEVADA), CAMBRIDGE MERCANTILE (AUSTRALIA) PTY. LTD. CAMBRIDGE MAY SELL TO YOU AND/OR BUY FROM YOU FOREIGN EXCHANGE INSTRUMENTS (INCLUDING SPOT AND/OR DERIVATIVE TRANSACTIONS; BOTH KINDS ARE HERE CALLED “FXI”S) COVERED BY CAMBRIDGE ON A PRINCIPAL BASIS. THIS DOCUMENT IS NOT: 1) ADVICE OF ANY KIND, OR 2) APPROVED OR REVIEWED BY ANY REGULATORY AUTHORITY, OR 3) AN OFFER TO SELL OR A SOLICITATION OF AN OFFER TO BUY ANY FXIS, OR TO PARTICIPATE IN ANY TRADING STRATEGY. BEFORE ACTING ON THIS DOCUMENT, YOU MUST CONSIDER THE APPROPRIATENESS OF THE INFORMATION, BASED ON YOUR OBJECTIVES, NEEDS AND FINANCES. FOR ADVICE, YOU MUST CONTACT SOMEONE INDEPENDENT OF CAMBRIDGE. CERTAIN FXIS MENTIONED IN THIS DOCUMENT MAY BE INELIGIBLE FOR SALE IN SOME LOCATIONS, AND/OR UNSUITABLE FOR YOU. CONTACT YOUR CAMBRIDGE REPRESENTATIVE FOR FURTHER INFORMATION REGARDING PRODUCT AVAILABILITY/SUITABILITY BEFORE YOU ENTER INTO ANY FXI CONTRACT. FXIS ARE VOLATILE AND MAY CAUSE LOSSES. PAST PERFORMANCE OF A FXI PRODUCT CANNOT BE RELIED ON TO DETERMINE FUTURE PERFORMANCE. THIS DOCUMENT IS INTENDED ONLY FOR PERSONS IN CANADA, THE US, AND AUSTRALIA. THIS DOCUMENT IS NOT INTENDED FOR PERSONS IN THE UK OR ELSEWHERE IN THE EEA.  IN AUSTRALIA, THIS PUBLICATION HAS BEEN DISTRIBUTED BY CAMBRIDGE MERCANTILE (AUSTRALIA) PTY. LTD. (ABN 85 126 642 448, AFSL 351278); FOR THE GENERAL INFORMATION OF ITS CUSTOMERS (AS DEFINED IN THE CORPORATIONS ACT 2001). THIS ENTITY MAKES NO REPRESENTATIONS THAT THE PRODUCTS OR SERVICES MENTIONED IN THIS DOCUMENT ARE AVAILABLE TO PERSONS IN AUSTRALIA OR ARE NECESSARILY SUITABLE FOR ANY PARTICULAR PERSON OR APPROPRIATE IN ACCORDANCE WITH LOCAL LAW. FEES MAY BE EARNED BY CAMBRIDGE (AND ITS AGENTS) IN RESPECT OF ANY BUSINESS TRANSACTED WITH CAMBRIDGE. THE DOCUMENT IS INTENDED TO BE DISTRIBUTED IN ITS ENTIRETY. UNLESS GOVERNING LAW PERMITS OTHERWISE, YOU MUST CONTACT THE APPLICABLE CAMBRIDGE IF YOU WISH TO USE CAMBRIDGE SERVICES TO ENTER A TRANSACTION INVOLVING ANY INSTRUMENT MENTIONED IN THIS DOCUMENT.</p>
        <p>© COPYRIGHT 2020, CAMBRIDGE MERCANTILE CORP., ALL RIGHTS RESERVED. NO PART OF THIS PUBLICATION MAY BE REPRODUCED, STORED IN A RETRIEVAL SYSTEM, OR TRANSMITTED, ON ANY FORM OR BY ANY MEANS, ELECTRONIC, MECHANICAL, PHOTOCOPYING, RECORDING, OR OTHERWISE, WITHOUT THE PRIOR WRITTEN PERMISSION OF CAMBRIDGE MERCANTILE CORP. SEE WWW.CAMBRIDGEFX.COM FOR CONTACT DETAILS.</p>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Disclosures',
}
</script>

<style>
.flex-container {
  display: flex;
}
.para {
  padding-left: 20px;
  padding-right: 20px;
  text-align: left;
}
</style>